import React, { useState } from 'react';

interface GroceryListProps {
  items: string[];
}

const GroceryList: React.FC<GroceryListProps> = ({ items }) => {
  const [checkedItems, setCheckedItems] = useState<Record<number, boolean>>({});

  const toggleItem = (index: number) => {
    setCheckedItems(prev => ({
      ...prev,
      [index]: !prev[index]
    }));
  };

  const handlePrintList = () => {
    const originalTitle = document.title;
    document.title = `采购清单_${new Date().toLocaleDateString()}.pdf`;
    
    // Add class to body to hide everything else
    document.body.classList.add('print-grocery-only');
    
    window.print();
    
    // Cleanup
    setTimeout(() => {
        document.body.classList.remove('print-grocery-only');
        document.title = originalTitle;
    }, 500);
  };

  return (
    <div className="grocery-print-container bg-white rounded-2xl shadow-sm border border-slate-200 p-6 relative group">
      <div className="flex justify-between items-start mb-4">
          <h2 className="text-xl font-bold text-slate-800 flex items-center">
            <svg xmlns="http://www.w3.org/2000/svg" className="h-6 w-6 mr-2 text-primary" fill="none" viewBox="0 0 24 24" stroke="currentColor">
              <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M16 11V7a4 4 0 00-8 0v4M5 9h14l1 12H4L5 9z" />
            </svg>
            本周采购清单 (待办)
          </h2>
          
          <button 
            onClick={handlePrintList}
            className="no-print text-sm bg-slate-100 hover:bg-slate-200 text-slate-600 px-3 py-1 rounded-lg font-bold transition-colors flex items-center"
          >
            <svg xmlns="http://www.w3.org/2000/svg" className="h-4 w-4 mr-1" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M4 16v1a3 3 0 003 3h10a3 3 0 003-3v-1m-4-4l-4 4m0 0l-4-4m4 4V4" />
            </svg>
            导出清单 PDF
          </button>
      </div>
      
      <p className="text-sm text-slate-500 mb-4 no-print">基于生成的7天食谱自动汇总。去超市前记得带上哦！</p>
      
      <div className="grid grid-cols-1 md:grid-cols-2 gap-3">
        {items.map((item, idx) => (
          <div 
            key={idx} 
            onClick={() => toggleItem(idx)}
            className={`
              flex items-center p-3 rounded-lg border cursor-pointer transition-all duration-200 break-inside-avoid
              ${checkedItems[idx] ? 'bg-slate-50 border-slate-100' : 'bg-white border-slate-200 hover:border-primary'}
            `}
          >
            <div className={`
              w-5 h-5 rounded border flex items-center justify-center mr-3 flex-shrink-0
              ${checkedItems[idx] ? 'bg-primary border-primary' : 'border-slate-300'}
            `}>
              {checkedItems[idx] && (
                <svg className="w-3 h-3 text-white" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                  <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={3} d="M5 13l4 4L19 7" />
                </svg>
              )}
            </div>
            <span className={`text-sm ${checkedItems[idx] ? 'text-slate-400 line-through' : 'text-slate-700'}`}>
              {item}
            </span>
          </div>
        ))}
      </div>
      
      {/* Footer for print only */}
      <div className="hidden print:block mt-8 pt-4 border-t border-slate-200 text-center text-xs text-slate-400">
        Generated by NutriGen AI
      </div>
    </div>
  );
};

export default GroceryList;